sudo: required
services:
  - docker

before_install:
  - docker build -t shakirah/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shakirah/docker-react npm run test

deploy:
  on:
    branch: master